# primary config
base_url = "https://bi-rabittoh.github.io"
title = "BiRabittoh's Site"
description = "A minimal website where I post stuff I'm passionate about."
default_language = "en"
minify_html = true

# blog
taxonomies = [
    { name = "category" },
    { name = "tags" },
]
