# primary config
base_url = "https://bi-rabittoh.github.io"
title = "Bi-Rabittoh's Site"
default_language = "en"
minify_html = true

# blog
taxonomies = [
    { name = "category" },
    { name = "tags" },
]
